baseURL = 'https://r1muru2006.github.io/'
languageCode = 'en-us'
title = "r1muru's blog"
theme = "reimu"

[markup.highlight]
guessSyntax = true
noClasses = false


[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true